In [1]:
import numpy as np
import cv2

In [2]:
image = cv2.imread('image.jpg')

## So as we can see it's a color image as it has 3 channels

In [3]:
image.shape

(339, 509, 3)

## To see the image

In [4]:
#cv2.imshow('Image',image)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

2024-08-23 12:48:23.206 Python[3330:30478] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


## To convert it to a grayscale image

In [6]:
image = cv2.imread('image.jpg',cv2.IMREAD_GRAYSCALE)

## Now as we can see it's a grayscale image

In [7]:
image.shape

(339, 509)

In [8]:
image

array([[  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [9]:
sobel_vertical = np.array([[-1,0,1],
                           [-2,0,2],
                           [-1,0,1]])

In [10]:
sobel_vertical

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [11]:
rows, cols = image.shape

In [12]:
rows

339

In [13]:
cols

509

In [14]:
rows, cols

(339, 509)

## As we know the resulted shape is n-k+1

In [15]:
k = sobel_vertical.shape[0]

In [16]:
k

3

## As we know np.zeros takes a tuple and create a matrix by tuple

In [18]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## So to create the output matrix we'll use the same n-k+1 formula

In [19]:
output_matrix = np.zeros((rows - k + 1, cols - k + 1))

In [20]:
output_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])